# Generated by Django 3.2.23 on 2024-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepmatsummary',
            name='apnea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='awake_in_bed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='out_of_bed_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='total_sleep_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='total_time_in_bed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(default='aggegated', max_length=20),
        ),
        migrations.AlterField(
            model_name='scale',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
