# Generated by Django 3.2.23 on 2024-06-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240604_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanwatchsummary',
            name='hr_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanwatchsummary',
            name='hr_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
