# Generated by Django 3.2.23 on 2024-06-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240604_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='scale_battery',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usage',
            name='scanwatch_battery',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usage',
            name='sleepmat_battery',
            field=models.CharField(max_length=10),
        ),
    ]
