# Generated by Django 3.2.23 on 2024-07-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240607_1721'),
        ('api', '0005_user_active'),
    ]

    operations = [
    ]
