# Generated by Django 3.2.23 on 2024-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_0005_auto_20240607_1721_0005_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepmatsummary',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
