# Generated by Django 5.0.7 on 2024-07-15 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240704_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AddField(
            model_name='scale',
            name='user',
            field=models.ForeignKey(default='27d7c8bb-c1b1-5c77-7279-5743b753c8a0', on_delete=django.db.models.deletion.CASCADE, related_name='scales_user', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanwatchintraactivity',
            name='user',
            field=models.ForeignKey(default='27d7c8bb-c1b1-5c77-7279-5743b753c8a0', on_delete=django.db.models.deletion.CASCADE, related_name='scanwatch_intraactivity_user', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanwatchsummary',
            name='user',
            field=models.ForeignKey(default='27d7c8bb-c1b1-5c77-7279-5743b753c8a0', on_delete=django.db.models.deletion.CASCADE, related_name='scanwatch_summary_user', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleepmatintraactivity',
            name='user',
            field=models.ForeignKey(default='27d7c8bb-c1b1-5c77-7279-5743b753c8a0', on_delete=django.db.models.deletion.CASCADE, related_name='sleepmat_intraactivity_user', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='user',
            field=models.ForeignKey(default='27d7c8bb-c1b1-5c77-7279-5743b753c8a0', on_delete=django.db.models.deletion.CASCADE, related_name='sleepmat_summary_user', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='withings_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='withings_credentials_path',
            field=models.CharField(default='27d7c8bb-c1b1-5c77-7279-5743b753c8a0', max_length=300),
            preserve_default=False,
        ),
    ]
