# Generated by Django 5.0.7 on 2024-07-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_device_user_scale_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scale_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scale_device_id', to='api.device'),
        ),
        migrations.AddField(
            model_name='user',
            name='scanwatch_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanwatch_device_id', to='api.device'),
        ),
        migrations.AddField(
            model_name='user',
            name='sleepmat_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleepmat_device_id', to='api.device'),
        ),
    ]
