# Generated by Django 5.0.7 on 2024-07-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_scale_device_user_scanwatch_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='bone_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scale',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scale',
            name='fat_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scale',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scale',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanwatchintraactivity',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanwatchintraactivity',
            name='date_calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanwatchintraactivity',
            name='date_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanwatchintraactivity',
            name='date_steps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanwatchintraactivity',
            name='heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanwatchintraactivity',
            name='steps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanwatchsummary',
            name='average_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanwatchsummary',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanwatchsummary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanwatchsummary',
            name='steps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatintraactivity',
            name='date_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatintraactivity',
            name='date_respiration_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatintraactivity',
            name='date_sdnn_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatintraactivity',
            name='date_snoring',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatintraactivity',
            name='end_date',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatintraactivity',
            name='heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatintraactivity',
            name='respiration_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatintraactivity',
            name='sdnn_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatintraactivity',
            name='sleep_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatintraactivity',
            name='snoring',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatintraactivity',
            name='start_date',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='average_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='average_rr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='breathing_disturbances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='deep_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='duration_to_sleep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='duration_to_wakeup',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='light_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='rem_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='sleep_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='wakeup_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmatsummary',
            name='wakeup_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='scale_battery',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='scale_last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='scale_usage_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='scanwatch_battery',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='scanwatch_last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='scanwatch_usage_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='sleepmat_battery',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='sleepmat_last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='sleepmat_usage_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
