# Generated by Django 5.0.7 on 2024-08-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_scale_bone_mass_alter_scale_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='report',
        ),
        migrations.AddField(
            model_name='usage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
