# Generated by Django 5.0.7 on 2024-08-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_usage_report_usage_end_date_usage_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='withings_credentials_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
