# Generated by Django 3.2.23 on 2024-08-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_withings_credentials_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepmatsummary',
            name='hr_af',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='hr_date_af',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='hr_date_rr',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmatsummary',
            name='hr_rr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
